window.COUNTRIES = [
  // --- AFRIKA ---
  { name: "Ägypten", continent: "Afrika" },
  { name: "Algerien", continent: "Afrika" },
  { name: "Angola", continent: "Afrika" },
  { name: "Äquatorialguinea", continent: "Afrika" },
  { name: "Äthiopien", continent: "Afrika" },
  { name: "Benin", continent: "Afrika" },
  { name: "Botswana", continent: "Afrika" },
  { name: "Burkina Faso", continent: "Afrika" },
  { name: "Burundi", continent: "Afrika" },
  { name: "Dschibuti", continent: "Afrika" },
  { name: "Elfenbeinküste", continent: "Afrika" },
  { name: "Eritrea", continent: "Afrika" },
  { name: "Eswatini", continent: "Afrika" },
  { name: "Gabun", continent: "Afrika" },
  { name: "Gambia", continent: "Afrika" },
  { name: "Ghana", continent: "Afrika" },
  { name: "Guinea", continent: "Afrika" },
  { name: "Guinea-Bissau", continent: "Afrika" },
  { name: "Kamerun", continent: "Afrika" },
  { name: "Kap Verde", continent: "Afrika" },
  { name: "Kenia", continent: "Afrika" },
  { name: "Komoren", continent: "Afrika" },
  { name: "Kongo, Demokratische Republik", continent: "Afrika" },
  { name: "Kongo, Republik", continent: "Afrika" },
  { name: "Lesotho", continent: "Afrika" },
  { name: "Liberia", continent: "Afrika" },
  { name: "Libyen", continent: "Afrika" },
  { name: "Madagaskar", continent: "Afrika" },
  { name: "Malawi", continent: "Afrika" },
  { name: "Mali", continent: "Afrika" },
  { name: "Marokko", continent: "Afrika" },
  { name: "Mauretanien", continent: "Afrika" },
  { name: "Mauritius", continent: "Afrika" },
  { name: "Mosambik", continent: "Afrika" },
  { name: "Namibia", continent: "Afrika" },
  { name: "Niger", continent: "Afrika" },
  { name: "Nigeria", continent: "Afrika" },
  { name: "Ruanda", continent: "Afrika" },
  { name: "Sambia", continent: "Afrika" },
  { name: "São Tomé und Príncipe", continent: "Afrika" },
  { name: "Senegal", continent: "Afrika" },
  { name: "Seychellen", continent: "Afrika" },
  { name: "Sierra Leone", continent: "Afrika" },
  { name: "Simbabwe", continent: "Afrika" },
  { name: "Somalia", continent: "Afrika" },
  { name: "Südafrika", continent: "Afrika" },
  { name: "Sudan", continent: "Afrika" },
  { name: "Südsudan", continent: "Afrika" },
  { name: "Tansania", continent: "Afrika" },
  { name: "Togo", continent: "Afrika" },
  { name: "Tschad", continent: "Afrika" },
  { name: "Tunesien", continent: "Afrika" },
  { name: "Uganda", continent: "Afrika" },
  { name: "Zentralafrikanische Republik", continent: "Afrika" },

  // --- ASIEN ---
  { name: "Afghanistan", continent: "Asien" },
  { name: "Armenien", continent: "Asien" },
  { name: "Aserbaidschan", continent: "Asien" },
  { name: "Bahrain", continent: "Asien" },
  { name: "Bangladesch", continent: "Asien" },
  { name: "Bhutan", continent: "Asien" },
  { name: "Brunei", continent: "Asien" },
  { name: "China", continent: "Asien" },
  { name: "Georgien", continent: "Asien" },
  { name: "Indien", continent: "Asien" },
  { name: "Indonesien", continent: "Asien" },
  { name: "Irak", continent: "Asien" },
  { name: "Iran", continent: "Asien" },
  { name: "Israel", continent: "Asien" },
  { name: "Japan", continent: "Asien" },
  { name: "Jemen", continent: "Asien" },
  { name: "Jordanien", continent: "Asien" },
  { name: "Kambodscha", continent: "Asien" },
  { name: "Kasachstan", continent: "Asien" },
  { name: "Katar", continent: "Asien" },
  { name: "Kirgisistan", continent: "Asien" },
  { name: "Kuwait", continent: "Asien" },
  { name: "Laos", continent: "Asien" },
  { name: "Libanon", continent: "Asien" },
  { name: "Malaysia", continent: "Asien" },
  { name: "Malediven", continent: "Asien" },
  { name: "Mongolei", continent: "Asien" },
  { name: "Myanmar", continent: "Asien" },
  { name: "Nepal", continent: "Asien" },
  { name: "Nordkorea", continent: "Asien" },
  { name: "Oman", continent: "Asien" },
  { name: "Pakistan", continent: "Asien" },
  { name: "Palästina", continent: "Asien" },
  { name: "Philippinen", continent: "Asien" },
  { name: "Saudi-Arabien", continent: "Asien" },
  { name: "Singapur", continent: "Asien" },
  { name: "Sri Lanka", continent: "Asien" },
  { name: "Südkorea", continent: "Asien" },
  { name: "Syrien", continent: "Asien" },
  { name: "Tadschikistan", continent: "Asien" },
  { name: "Thailand", continent: "Asien" },
  { name: "Timor-Leste", continent: "Asien" },
  { name: "Türkei", continent: "Asien" },
  { name: "Turkmenistan", continent: "Asien" },
  { name: "Usbekistan", continent: "Asien" },
  { name: "Vereinigte Arabische Emirate", continent: "Asien" },
  { name: "Vietnam", continent: "Asien" },

  // --- EUROPA ---
  { name: "Albanien", continent: "Europa" },
  { name: "Andorra", continent: "Europa" },
  { name: "Belgien", continent: "Europa" },
  { name: "Bosnien und Herzegowina", continent: "Europa" },
  { name: "Bulgarien", continent: "Europa" },
  { name: "Dänemark", continent: "Europa" },
  { name: "Deutschland", continent: "Europa" },
  { name: "Estland", continent: "Europa" },
  { name: "Finnland", continent: "Europa" },
  { name: "Frankreich", continent: "Europa" },
  { name: "Griechenland", continent: "Europa" },
  { name: "Irland", continent: "Europa" },
  { name: "Island", continent: "Europa" },
  { name: "Italien", continent: "Europa" },
  { name: "Kasachstan", continent: "Europa" },
  { name: "Kosovo", continent: "Europa" },
  { name: "Kroatien", continent: "Europa" },
  { name: "Lettland", continent: "Europa" },
  { name: "Liechtenstein", continent: "Europa" },
  { name: "Litauen", continent: "Europa" },
  { name: "Luxemburg", continent: "Europa" },
  { name: "Malta", continent: "Europa" },
  { name: "Moldau", continent: "Europa" },
  { name: "Monaco", continent: "Europa" },
  { name: "Montenegro", continent: "Europa" },
  { name: "Niederlande", continent: "Europa" },
  { name: "Nordmazedonien", continent: "Europa" },
  { name: "Norwegen", continent: "Europa" },
  { name: "Österreich", continent: "Europa" },
  { name: "Polen", continent: "Europa" },
  { name: "Portugal", continent: "Europa" },
  { name: "Rumänien", continent: "Europa" },
  { name: "Russland", continent: "Europa" },
  { name: "San Marino", continent: "Europa" },
  { name: "Schweden", continent: "Europa" },
  { name: "Schweiz", continent: "Europa" },
  { name: "Serbien", continent: "Europa" },
  { name: "Slowakei", continent: "Europa" },
  { name: "Slowenien", continent: "Europa" },
  { name: "Spanien", continent: "Europa" },
  { name: "Tschechien", continent: "Europa" },
  { name: "Ukraine", continent: "Europa" },
  { name: "Ungarn", continent: "Europa" },
  { name: "Vatikanstadt", continent: "Europa" },
  { name: "Vereinigtes Königreich", continent: "Europa" },
  { name: "Belarus", continent: "Europa" },
  { name: "Zypern", continent: "Europa" },

  // --- NORDAMERIKA ---
  { name: "Antigua und Barbuda", continent: "Nordamerika" },
  { name: "Bahamas", continent: "Nordamerika" },
  { name: "Barbados", continent: "Nordamerika" },
  { name: "Belize", continent: "Nordamerika" },
  { name: "Costa Rica", continent: "Nordamerika" },
  { name: "Dominica", continent: "Nordamerika" },
  { name: "Dominikanische Republik", continent: "Nordamerika" },
  { name: "El Salvador", continent: "Nordamerika" },
  { name: "Grenada", continent: "Nordamerika" },
  { name: "Guatemala", continent: "Nordamerika" },
  { name: "Haiti", continent: "Nordamerika" },
  { name: "Honduras", continent: "Nordamerika" },
  { name: "Jamaika", continent: "Nordamerika" },
  { name: "Kanada", continent: "Nordamerika" },
  { name: "Kuba", continent: "Nordamerika" },
  { name: "Mexiko", continent: "Nordamerika" },
  { name: "Nicaragua", continent: "Nordamerika" },
  { name: "Panama", continent: "Nordamerika" },
  { name: "St. Kitts und Nevis", continent: "Nordamerika" },
  { name: "St. Lucia", continent: "Nordamerika" },
  { name: "St. Vincent und die Grenadinen", continent: "Nordamerika" },
  { name: "Trinidad und Tobago", continent: "Nordamerika" },
  { name: "USA", continent: "Nordamerika" },

  // --- SÜDAMERIKA ---
  { name: "Argentinien", continent: "Südamerika" },
  { name: "Bolivien", continent: "Südamerika" },
  { name: "Brasilien", continent: "Südamerika" },
  { name: "Chile", continent: "Südamerika" },
  { name: "Ecuador", continent: "Südamerika" },
  { name: "Guyana", continent: "Südamerika" },
  { name: "Kolumbien", continent: "Südamerika" },
  { name: "Paraguay", continent: "Südamerika" },
  { name: "Peru", continent: "Südamerika" },
  { name: "Suriname", continent: "Südamerika" },
  { name: "Uruguay", continent: "Südamerika" },
  { name: "Venezuela", continent: "Südamerika" },

  // --- OZEANIEN ---
  { name: "Australien", continent: "Ozeanien" },
  { name: "Fidschi", continent: "Ozeanien" },
  { name: "Kiribati", continent: "Ozeanien" },
  { name: "Marshallinseln", continent: "Ozeanien" },
  { name: "Mikronesien", continent: "Ozeanien" },
  { name: "Nauru", continent: "Ozeanien" },
  { name: "Neuseeland", continent: "Ozeanien" },
  { name: "Palau", continent: "Ozeanien" },
  { name: "Papua-Neuguinea", continent: "Ozeanien" },
  { name: "Salomonen", continent: "Ozeanien" },
  { name: "Samoa", continent: "Ozeanien" },
  { name: "Tonga", continent: "Ozeanien" },
  { name: "Tuvalu", continent: "Ozeanien" },
  { name: "Vanuatu", continent: "Ozeanien" }
];